[project]
name = "deep-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[google-genai,litellm,tools]>=1.15.12",
    "crewai-tools>=1.15.12",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
    "tavily-python>=0.7.27",
    "litellm>=1.100.0",
    "groq>=1.7.0",
    "composio-crewai>=0.21.1",
    "reportlab>=5.0.1",
]

[project.scripts]
deep-research-agent = "deep_research_agent:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
